version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql_mode=
    restart: on-failure
    environment:
      - MYSQL_DATABASE=EV
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_INITDB_SKIP_TZINFO=1
    expose:
      - "3306"
    ports:
      - '3306:3306'
    volumes:
      - mysql_db:/var/lib/mysql
  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres_db:/data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: on-failure
  fastapi-docker:
    container_name: fastapi-docker
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql_db

volumes:
  mysql_db:
  redis:
  postgres_db:
  fastapi-docker:
