default: &default
  DB_DATABASE: EV
  DB_HOST: localhost
  DB_POST: 3306
  DB_URL: mysql+pymysql://root:123456@localhost:3306/EV
  DB_USER: root
  DB_PASS: 123456
  ENVIRONMENT: local
  API_PREFIX: "/api"
  ORIGINS: ["*"]
  TITLE: "Template FastApi Local"
  DESCRIPTION: "Template fast api local"
  VERSION: "0.1.0"


  ACCESS_TOKEN_EXPIRES_IN: 30
  REFRESH_TOKEN_EXPIRES_IN: 60
  JWT_ALGORITHM: HS256
  JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT2dJQkFBSkJBSSs3QnZUS0FWdHVQYzEzbEFkVk94TlVmcWxzMm1SVmlQWlJyVFpjd3l4RVhVRGpNaFZuCi9KVHRsd3h2a281T0pBQ1k3dVE0T09wODdiM3NOU3ZNd2xNQ0F3RUFBUUpBYm5LaENOQ0dOSFZGaHJPQ0RCU0IKdmZ2ckRWUzVpZXAwd2h2SGlBUEdjeWV6bjd0U2RweUZ0NEU0QTNXT3VQOXhqenNjTFZyb1pzRmVMUWlqT1JhUwp3UUloQU84MWl2b21iVGhjRkltTFZPbU16Vk52TGxWTW02WE5iS3B4bGh4TlpUTmhBaUVBbWRISlpGM3haWFE0Cm15QnNCeEhLQ3JqOTF6bVFxU0E4bHUvT1ZNTDNSak1DSVFEbDJxOUdtN0lMbS85b0EyaCtXdnZabGxZUlJPR3oKT21lV2lEclR5MUxaUVFJZ2ZGYUlaUWxMU0tkWjJvdXF4MHdwOWVEejBEWklLVzVWaSt6czdMZHRDdUVDSUVGYwo3d21VZ3pPblpzbnU1clBsTDJjZldLTGhFbWwrUVFzOCtkMFBGdXlnCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBSSs3QnZUS0FWdHVQYzEzbEFkVk94TlVmcWxzMm1SVgppUFpSclRaY3d5eEVYVURqTWhWbi9KVHRsd3h2a281T0pBQ1k3dVE0T09wODdiM3NOU3ZNd2xNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==


local:
  <<: *default


local_test:
  <<: *default
  DB_DATABASE: db_test
  ENVIRONMENT: local_test
  DB_URL: mysql+pymysql://root:123456@localhost:3306/db_test
  SQLALCHEMY_ECHO: False

local_dev:
  <<: *default
  DB_DATABASE: local_dev
  ENVIRONMENT: local_dev

test:
  <<: *default
  DB_DATABASE: test
  ENVIRONMENT: test

develop:
  <<: *default
  DB_DATABASE: develop
  ENVIRONMENT: develop

stage:
  <<: *default
  DB_DATABASE: stage
  ENVIRONMENT: stage

production:
  <<: *default
  DB_DATABASE: product
  ENVIRONMENT: product
