"""sample revision message

Revision ID: 163b3cdf97a5
Revises: 
Create Date: 2022-08-26 15:10:10.309945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163b3cdf97a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charger_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charger_model_id'), 'charger_model', ['id'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=True)
    op.create_table('division',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_division_id'), 'division', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('hash_password', sa.String(length=255), nullable=True),
    sa.Column('creation', sa.DATETIME(), nullable=True),
    sa.Column('modified', sa.DATETIME(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('role_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vehicle_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('modified', sa.String(length=255), nullable=True),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_model_id'), 'vehicle_model', ['id'], unique=True)
    op.create_table('charger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('charger_pdi_status', sa.String(length=255), nullable=True),
    sa.Column('manufactoring_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['charger_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charger_id'), 'charger', ['id'], unique=True)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('system_user', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=True)
    op.create_table('sale_information',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('sale_order_number', sa.String(length=255), nullable=True),
    sa.Column('sale_type', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('vehicle_warranty', sa.Integer(), nullable=True),
    sa.Column('battery_warranty', sa.Integer(), nullable=True),
    sa.Column('battery_maintenance', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('product_number', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.Column('working_days', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contract_no', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_information_id'), 'sale_information', ['id'], unique=True)
    op.create_table('electric_vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('vehicle_number', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('car_condition', sa.String(length=255), nullable=True),
    sa.Column('forklift_pdi_status', sa.String(length=255), nullable=True),
    sa.Column('import_date', sa.Date(), nullable=True),
    sa.Column('asset_register_date', sa.Date(), nullable=True),
    sa.Column('delivering_date', sa.Date(), nullable=True),
    sa.Column('edge_id', sa.String(length=255), nullable=True),
    sa.Column('operating_hours', sa.String(length=255), nullable=True),
    sa.Column('operating_mileage', sa.String(length=255), nullable=True),
    sa.Column('initial_operating_hours', sa.Float(), nullable=True),
    sa.Column('initial_operating_mileage', sa.Float(), nullable=True),
    sa.Column('operation_status', sa.String(length=255), nullable=True),
    sa.Column('mileage_value', sa.String(length=255), nullable=True),
    sa.Column('hr', sa.String(length=255), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('charger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charger_id'], ['charger.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_model.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electric_vehicle_id'), 'electric_vehicle', ['id'], unique=True)
    op.create_table('vehicle_division',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_division_id'), 'vehicle_division', ['id'], unique=True)
    op.create_table('vehicle_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('update_by', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('amended_from', sa.String(length=255), nullable=True),
    sa.Column('islatest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_history_id'), 'vehicle_history', ['id'], unique=True)
    op.create_table('work_shift',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('workings_day', sa.String(length=255), nullable=True),
    sa.Column('work_shift', sa.String(length=255), nullable=True),
    sa.Column('work_shift_from', sa.String(length=255), nullable=True),
    sa.Column('work_shift_to', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['electric_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_shift_id'), 'work_shift', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_shift_id'), table_name='work_shift')
    op.drop_table('work_shift')
    op.drop_index(op.f('ix_vehicle_history_id'), table_name='vehicle_history')
    op.drop_table('vehicle_history')
    op.drop_index(op.f('ix_vehicle_division_id'), table_name='vehicle_division')
    op.drop_table('vehicle_division')
    op.drop_index(op.f('ix_electric_vehicle_id'), table_name='electric_vehicle')
    op.drop_table('electric_vehicle')
    op.drop_index(op.f('ix_sale_information_id'), table_name='sale_information')
    op.drop_table('sale_information')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_charger_id'), table_name='charger')
    op.drop_table('charger')
    op.drop_index(op.f('ix_vehicle_model_id'), table_name='vehicle_model')
    op.drop_table('vehicle_model')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_division_id'), table_name='division')
    op.drop_table('division')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_charger_model_id'), table_name='charger_model')
    op.drop_table('charger_model')
    # ### end Alembic commands ###
