"""sample revision message

Revision ID: f58c8a015756
Revises: 163b3cdf97a5
Create Date: 2022-08-26 15:15:44.235556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58c8a015756'
down_revision = '163b3cdf97a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
