from .contract_expire_report_router import contract_expire_router
from .pdi_status_chart_router import pdi_status_chart_router
from .sale_type_stats_router import sale_type_stats_router
from .vehicle_by_location_router import vehicle_by_location_router

contract_expire_router = contract_expire_router
pdi_status_chart_router = pdi_status_chart_router
sale_type_stats_router = sale_type_stats_router
vehicle_by_location_router = vehicle_by_location_router
