from .contract_expire_overview_router import contract_expire_overview_router
from .contract_expire_report_router import contract_expire_router
from .get_total_router import get_total_overview_router
from .operation_status_report_router import operation_status_report_router
from .pdi_status_chart_router import pdi_status_chart_router
from .sale_type_stats_router import sale_type_stats_router
from .vehicle_by_location_router import vehicle_by_location_router

contract_expire_router = contract_expire_router
pdi_status_chart_router = pdi_status_chart_router
sale_type_stats_router = sale_type_stats_router
vehicle_by_location_router = vehicle_by_location_router
get_total_overview_router = get_total_overview_router
operation_status_report_router = operation_status_report_router
contract_expire_overview_router = contract_expire_overview_router
