name: FastAPI CI/CD

on: [push, pull_request]

jobs:

  flake8:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.7
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true

  docker_cicd:
    name: Build and push Docker image to Docker Hub
    # ...but only when a `release` is `published` (combined with `on`)
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
